### get request
GET http://localhost:8000/

### get single or all task from server
GET  http://localhost:8000/api/v1/task/

### post task from server
POST  http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task" : "walking",
    "hr" : 6
}

### Patch task from server
PATCH   http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id": "62676c95e417b1aa41b48332",
    "task" : "program"
}

### delete task from server
DELETE  http://localhost:8000/api/v1/task/62676c9ce417b1aa41b48334
