### get request
GET http://localhost:8000/

### get single or all task from server
GET  http://localhost:8000/api/v1/task/

### post task to server
POST  http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task" : "dance",
    "hr" : 150,
    "userID" : "6278879a251f319ac59757e1"
}

### Patch task from server
PATCH   http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id": "62676c95e417b1aa41b48332",
    "task" : "program"
}

### delete task from server
DELETE  http://localhost:8000/api/v1/task/


# user api zone

### get user
GET http://localhost:8000/api/v1/user/

### post user
POST http://localhost:8000/api/v1/user/
Content-Type: application/json

{
    "name" : "Mer",
    "email": "mer@email.com"
}

### delete user
DELETE  http://localhost:8000/api/v1/user/62787017d5bad1ac9bee337d